Running experiments with C=800
Configuration:
- Number of experiments: 100
- MCTS simulations: 250
- Parallel units: 32
- MCTS type: explorescore
- C value: 800

Compiling with MCTS_TYPE=explorescore...
rm -f game2048
g++ -Wall -Wextra -std=c++17 -O3 -fopenmp -I. -DUSE_EXPLORE_SCORE main.cpp env2048.cpp pUCT/mcts_pUCT.cpp -o game2048
main.cpp: In function ‘int main(int, char**)’:
main.cpp:97:63: error: too many arguments to function ‘GameStats run_game(int, int)’
     auto stats = run_game(num_boards, num_simulations, c_param);
                                                               ^
main.cpp:38:11: note: declared here
 GameStats run_game(int num_boards, int num_simulations) {
           ^~~~~~~~
make: *** [makefile:32: game2048] Error 1
Compilation failed
Error processing results: [Errno 2] No such file or directory: 'data/explorescore_sims100_C800_20241209_215432.csv'
Traceback (most recent call last):
  File "/net/rcstorenfs02/ifs/rc_labs/idreos_lab/users/vcainamisir/2048/2048rl/cpp/plotting/plot_results.py", line 122, in <module>
    main()
  File "/net/rcstorenfs02/ifs/rc_labs/idreos_lab/users/vcainamisir/2048/2048rl/cpp/plotting/plot_results.py", line 115, in main
    output_path = analyze_and_plot(args.csv_file)
  File "/net/rcstorenfs02/ifs/rc_labs/idreos_lab/users/vcainamisir/2048/2048rl/cpp/plotting/plot_results.py", line 79, in analyze_and_plot
    df = pd.read_csv(csv_path)
  File "/n/home06/vcainamisir/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/n/home06/vcainamisir/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/n/home06/vcainamisir/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/n/home06/vcainamisir/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/n/home06/vcainamisir/.local/lib/python3.10/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/explorescore_sims100_C800_20241209_215432.csv'
Running experiments with C=900
Configuration:
- Number of experiments: 100
- MCTS simulations: 250
- Parallel units: 32
- MCTS type: explorescore
- C value: 900

Compiling with MCTS_TYPE=explorescore...
rm -f game2048
g++ -Wall -Wextra -std=c++17 -O3 -fopenmp -I. -DUSE_EXPLORE_SCORE main.cpp env2048.cpp pUCT/mcts_pUCT.cpp -o game2048
main.cpp: In function ‘int main(int, char**)’:
main.cpp:97:63: error: too many arguments to function ‘GameStats run_game(int, int)’
     auto stats = run_game(num_boards, num_simulations, c_param);
                                                               ^
main.cpp:38:11: note: declared here
 GameStats run_game(int num_boards, int num_simulations) {
           ^~~~~~~~
make: *** [makefile:32: game2048] Error 1
Compilation failed
Error processing results: [Errno 2] No such file or directory: 'data/explorescore_sims100_C900_20241209_215432.csv'
Traceback (most recent call last):
  File "/net/rcstorenfs02/ifs/rc_labs/idreos_lab/users/vcainamisir/2048/2048rl/cpp/plotting/plot_results.py", line 122, in <module>
    main()
  File "/net/rcstorenfs02/ifs/rc_labs/idreos_lab/users/vcainamisir/2048/2048rl/cpp/plotting/plot_results.py", line 115, in main
    output_path = analyze_and_plot(args.csv_file)
  File "/net/rcstorenfs02/ifs/rc_labs/idreos_lab/users/vcainamisir/2048/2048rl/cpp/plotting/plot_results.py", line 79, in analyze_and_plot
    df = pd.read_csv(csv_path)
  File "/n/home06/vcainamisir/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/n/home06/vcainamisir/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/n/home06/vcainamisir/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/n/home06/vcainamisir/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/n/home06/vcainamisir/.local/lib/python3.10/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/explorescore_sims100_C900_20241209_215432.csv'
Running experiments with C=1000
Configuration:
- Number of experiments: 100
- MCTS simulations: 250
- Parallel units: 32
- MCTS type: explorescore
- C value: 1000

Compiling with MCTS_TYPE=explorescore...
rm -f game2048
g++ -Wall -Wextra -std=c++17 -O3 -fopenmp -I. -DUSE_EXPLORE_SCORE main.cpp env2048.cpp pUCT/mcts_pUCT.cpp -o game2048
main.cpp: In function ‘int main(int, char**)’:
main.cpp:97:63: error: too many arguments to function ‘GameStats run_game(int, int)’
     auto stats = run_game(num_boards, num_simulations, c_param);
                                                               ^
main.cpp:38:11: note: declared here
 GameStats run_game(int num_boards, int num_simulations) {
           ^~~~~~~~
make: *** [makefile:32: game2048] Error 1
Compilation failed
Error processing results: [Errno 2] No such file or directory: 'data/explorescore_sims100_C1000_20241209_215432.csv'
Traceback (most recent call last):
  File "/net/rcstorenfs02/ifs/rc_labs/idreos_lab/users/vcainamisir/2048/2048rl/cpp/plotting/plot_results.py", line 122, in <module>
    main()
  File "/net/rcstorenfs02/ifs/rc_labs/idreos_lab/users/vcainamisir/2048/2048rl/cpp/plotting/plot_results.py", line 115, in main
    output_path = analyze_and_plot(args.csv_file)
  File "/net/rcstorenfs02/ifs/rc_labs/idreos_lab/users/vcainamisir/2048/2048rl/cpp/plotting/plot_results.py", line 79, in analyze_and_plot
    df = pd.read_csv(csv_path)
  File "/n/home06/vcainamisir/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/n/home06/vcainamisir/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/n/home06/vcainamisir/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/n/home06/vcainamisir/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/n/home06/vcainamisir/.local/lib/python3.10/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/explorescore_sims100_C1000_20241209_215432.csv'
Running experiments with C=1100
Configuration:
- Number of experiments: 100
- MCTS simulations: 250
- Parallel units: 32
- MCTS type: explorescore
- C value: 1100

Compiling with MCTS_TYPE=explorescore...
rm -f game2048
g++ -Wall -Wextra -std=c++17 -O3 -fopenmp -I. -DUSE_EXPLORE_SCORE main.cpp env2048.cpp pUCT/mcts_pUCT.cpp -o game2048
main.cpp: In function ‘int main(int, char**)’:
main.cpp:97:63: error: too many arguments to function ‘GameStats run_game(int, int)’
     auto stats = run_game(num_boards, num_simulations, c_param);
                                                               ^
main.cpp:38:11: note: declared here
 GameStats run_game(int num_boards, int num_simulations) {
           ^~~~~~~~
make: *** [makefile:32: game2048] Error 1
Compilation failed
Error processing results: [Errno 2] No such file or directory: 'data/explorescore_sims100_C1100_20241209_215432.csv'
Traceback (most recent call last):
  File "/net/rcstorenfs02/ifs/rc_labs/idreos_lab/users/vcainamisir/2048/2048rl/cpp/plotting/plot_results.py", line 122, in <module>
    main()
  File "/net/rcstorenfs02/ifs/rc_labs/idreos_lab/users/vcainamisir/2048/2048rl/cpp/plotting/plot_results.py", line 115, in main
    output_path = analyze_and_plot(args.csv_file)
  File "/net/rcstorenfs02/ifs/rc_labs/idreos_lab/users/vcainamisir/2048/2048rl/cpp/plotting/plot_results.py", line 79, in analyze_and_plot
    df = pd.read_csv(csv_path)
  File "/n/home06/vcainamisir/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/n/home06/vcainamisir/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/n/home06/vcainamisir/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/n/home06/vcainamisir/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/n/home06/vcainamisir/.local/lib/python3.10/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/explorescore_sims100_C1100_20241209_215432.csv'
Running experiments with C=1200
Configuration:
- Number of experiments: 100
- MCTS simulations: 250
- Parallel units: 32
- MCTS type: explorescore
- C value: 1200

Compiling with MCTS_TYPE=explorescore...
rm -f game2048
g++ -Wall -Wextra -std=c++17 -O3 -fopenmp -I. -DUSE_EXPLORE_SCORE main.cpp env2048.cpp pUCT/mcts_pUCT.cpp -o game2048
main.cpp: In function ‘int main(int, char**)’:
main.cpp:97:63: error: too many arguments to function ‘GameStats run_game(int, int)’
     auto stats = run_game(num_boards, num_simulations, c_param);
                                                               ^
main.cpp:38:11: note: declared here
 GameStats run_game(int num_boards, int num_simulations) {
           ^~~~~~~~
make: *** [makefile:32: game2048] Error 1
Compilation failed
Error processing results: [Errno 2] No such file or directory: 'data/explorescore_sims100_C1200_20241209_215432.csv'
Traceback (most recent call last):
  File "/net/rcstorenfs02/ifs/rc_labs/idreos_lab/users/vcainamisir/2048/2048rl/cpp/plotting/plot_results.py", line 122, in <module>
    main()
  File "/net/rcstorenfs02/ifs/rc_labs/idreos_lab/users/vcainamisir/2048/2048rl/cpp/plotting/plot_results.py", line 115, in main
    output_path = analyze_and_plot(args.csv_file)
  File "/net/rcstorenfs02/ifs/rc_labs/idreos_lab/users/vcainamisir/2048/2048rl/cpp/plotting/plot_results.py", line 79, in analyze_and_plot
    df = pd.read_csv(csv_path)
  File "/n/home06/vcainamisir/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/n/home06/vcainamisir/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/n/home06/vcainamisir/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/n/home06/vcainamisir/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/n/home06/vcainamisir/.local/lib/python3.10/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/explorescore_sims100_C1200_20241209_215432.csv'
Combining results and creating comparison plots...
Traceback (most recent call last):
  File "/net/rcstorenfs02/ifs/rc_labs/idreos_lab/users/vcainamisir/2048/2048rl/cpp/plotting/compare_results.py", line 86, in <module>
    main()
  File "/net/rcstorenfs02/ifs/rc_labs/idreos_lab/users/vcainamisir/2048/2048rl/cpp/plotting/compare_results.py", line 83, in main
    combine_and_compare_results(data_dir, pattern)
  File "/net/rcstorenfs02/ifs/rc_labs/idreos_lab/users/vcainamisir/2048/2048rl/cpp/plotting/compare_results.py", line 34, in combine_and_compare_results
    combined_df = pd.concat(all_data, ignore_index=True)
  File "/n/home06/vcainamisir/.local/lib/python3.10/site-packages/pandas/core/reshape/concat.py", line 382, in concat
    op = _Concatenator(
  File "/n/home06/vcainamisir/.local/lib/python3.10/site-packages/pandas/core/reshape/concat.py", line 445, in __init__
    objs, keys = self._clean_keys_and_objs(objs, keys)
  File "/n/home06/vcainamisir/.local/lib/python3.10/site-packages/pandas/core/reshape/concat.py", line 507, in _clean_keys_and_objs
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
